## makeCacheMatrix takes an invertible 
## matrix as an input parameter x
## and prepares a list of four functions 
## that are needed to pass as an input
## parameter to cacheSolve().
##
## The four functions are:
##  1. set - Sets the matrix x.
##  2. get - Returns the matrix x.
##  3. set_inverse - Sets the inverse of matrix x in the cache
##  4. get_inverse - Retrieves the inverse of matrix x from the cache
makeCacheMatrix <- function(x = matrix()) {
    x_inverse <- NULL
    set <- function(y) {
        x <<- y                                       ## set matrix x
        x_inverse <<- NULL                            ## set cached matrix inverse to NULL indicating 
                                                      ## the matrix inverse needs to be computed
    }
    get <- function() x                               ## retrieve matrix x
    set_inverse <- function(inv) x_inverse <<- inv    ## store matrix inverse in cache
    get_inverse <- function() x_inverse               ## retrieve matrix inverse from cache
    list(set = set, get = get,
         set_inverse = set_inverse,
         get_inverse = get_inverse)
}


## CacheSolve takes an input x which is the
## function list generated by mackCacheMatrix for an 
## invertible matrix x. CacheSolve then either 
## retrieves the inverse of matrix x from the 
## cache if the matrix inverse has already been 
## computed or finds the inverse of matrix x via the 
## solve() function if the matrix inverse has 
## not already been computed and cached.
cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        x_inverse <- x$get_inverse()     ## retrive matrix inverse from cache
        if (!is.null(x_inverse)) {
            message("getting cached matrix inverse")
            return(x_inverse)            ## return matrix inverse if it existed in cache
        }
        data <- x$get()                  ## retrieve matrix x via the get() function in the list
        x_inverse <- solve(data)         ## compute matrix inverse via solve() function.
        x$set_inverse(x_inverse)         ## store matrix inverse in cache using set_inverse() function in the list
        x_inverse                        ## return matrix inverse of x
}
